import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { Trace, SpanKind, httpAttrs } from "./otel.ts";

// The public "Tell us what needs doing" form on yaadly.co.uk posts here
// directly. This used to write to an intakes staging table and then bounce
// the visitor out to WhatsApp, requiring Monique to manually convert it into
// a job later. The form already collects structured fields, name, email,
// address, trade, and so on, so no AI extraction step is needed the way a
// raw WhatsApp message needs one. This function skips the staging step
// entirely and creates the job directly, same portal_code model as every
// other job-creation path (admin desk, WhatsApp webhook): the code is
// generated by the database the moment the row exists, not before.
// verify_jwt is off because the visitor submitting this form has no session
// at all, this is a public form endpoint, the same trust level the old
// direct-to-Supabase intakes insert already had.
//
// Note the evidence insert below runs on the service-role client, so it is
// unaffected by the row-level security policy that restricts browser-side
// evidence inserts to the parties attached to a job.
//
// Package 1 guards, 24 Aug 2026: the property address and access contact
// used to be embedded in descr, and descr is published to ANYONE by the
// open_jobs view the moment a job is opened for quotes. They now live in
// their own columns (addr, access_contact) and descr stays clean. The
// function also pushes a notification to Monique's phone via ntfy.sh (free,
// topic held in app_settings, payload carries no client contact details),
// because the site promises a reply within 24 hours and until now nothing
// told her a request had arrived.

const CORS = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS" };

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });

  const trace = new Trace("yaad-website-intake", req);
  const root = trace.startSpan(`${req.method} /yaad-website-intake`, SpanKind.SERVER, httpAttrs(req));
  const done = (res: Response, status: number) => {
    root.setAttributes({ "http.response.status_code": status });
    root.end();
    trace.flush();
    return res;
  };

  if (req.method !== "POST") return done(new Response("Method not allowed", { status: 405, headers: CORS }), 405);

  let body: any = {};
  try { body = await req.json(); } catch (_) { /* fall through to validation */ }

  const name = String(body.name || "").trim();
  const phone = String(body.phone || "").trim();
  const email = String(body.email || "").trim();
  const desc = String(body.desc || "").trim();

  if (!name || !phone || !email || !desc) {
    root.setAttributes({ "yaadly.intake.outcome": "validation_failed" });
    return done(new Response(JSON.stringify({ error: "Name, WhatsApp number, email and a description are all required." }), { status: 400, headers: { ...CORS, "Content-Type": "application/json" } }), 400);
  }

  const parish = String(body.parish || "").trim();
  const addr = String(body.addr || "").trim();
  const access = String(body.access || "").trim();
  const workType = String(body.workType || "").trim();
  const urgency = String(body.urgency || "As soon as possible").trim();
  const clientLocation = String(body.clientLocation || "").trim();
  const photos: string[] = Array.isArray(body.photos) ? body.photos.slice(0, 8) : [];

  const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

  const jobId = `JOB-WEB-${Date.now()}`;
  const title = workType ? `${workType} request from ${name}` : `Job request from ${name}`;
  // Contact details deliberately NOT in descr: the open_jobs view publishes
  // descr to the public board. Address and access contact go in their own
  // columns, visible only to the assigned worker, the client and the admin.
  const descr = [
    desc,
    urgency ? `When: ${urgency}` : "",
    clientLocation ? `Client is: ${clientLocation}` : "",
    workType ? `Trade: ${workType}` : "",
    `Submitted via the website request form.`
  ].filter(Boolean).join("\n");

  root.setAttributes({
    "yaadly.job.id": jobId,
    "yaadly.job.source": "website_form",
    "yaadly.job.trade": workType,
    "yaadly.job.parish": parish,
    "yaadly.intake.photo_count": photos.length,
  });

  const { inserted, insertError } = await trace.span("db.insert jobs", SpanKind.CLIENT, {
    "db.system.name": "postgresql",
    "db.operation.name": "INSERT",
    "db.collection.name": "jobs",
    "yaadly.job.id": jobId,
  }, async (s) => {
    const { data, error } = await supabase.from("jobs").insert({
      id: jobId,
      title,
      parish,
      client_name: name,
      client_email: email.toLowerCase(),
      client_phone: phone,
      descr,
      addr,
      access_contact: access,
      // The wizard already asks for this at step 1; until now it was written
      // into descr and the trace and then thrown away, so every job arrived
      // with no trade and matched nobody. Stored raw: the trg_normalise_job_trade
      // trigger runs it through trade_key() so there is one normalisation
      // point and no TypeScript copy of that regex to drift.
      trade: workType || null,
      trade_source: workType ? "wizard" : null,
      stage: 0,
      open: false
    }).select("portal_code").single();
    if (error) s.recordError(error.message);
    s.setAttributes({ "yaadly.job.portal_code_issued": Boolean(data?.portal_code) });
    return { inserted: data, insertError: error };
  });

  if (insertError) {
    root.setAttributes({ "yaadly.intake.outcome": "job_insert_failed" });
    return done(new Response(JSON.stringify({ error: insertError.message }), { status: 500, headers: { ...CORS, "Content-Type": "application/json" } }), 500);
  }

  if (photos.length) {
    await trace.span("db.insert evidence", SpanKind.CLIENT, {
      "db.system.name": "postgresql",
      "db.operation.name": "INSERT",
      "db.collection.name": "evidence",
      "yaadly.evidence.row_count": photos.length,
      "yaadly.evidence.source": "client_upload",
    }, async (s) => {
      const rows = photos.map((img, i) => ({ job_id: jobId, label: `Client photo ${i + 1}`, meta: "From website request form", img, ok: true }));
      const { error: evErr } = await supabase.from("evidence").insert(rows);
      if (evErr) {
        s.recordError(evErr.message);
        console.warn("evidence insert:", evErr.message);
      }
    });
  }

  root.setAttributes({ "yaadly.intake.outcome": "job_created" });

  // Tell Monique. Fire and forget: a notification relay being down must
  // never fail the client's request. No names, addresses or numbers leave
  // for the relay, only the reference, trade and parish.
  const notify = (async () => {
    try {
      const { data: st } = await supabase.from("app_settings").select("value").eq("key", "ntfy_topic").single();
      if (!st?.value) return;
      await fetch(`https://ntfy.sh/${st.value}`, {
        method: "POST",
        headers: { Title: "New Yaadly request", Priority: "high", Tags: "house" },
        body: `${jobId}: ${workType || "job"}, ${parish || "parish not given"}. Reply promised within 24 hours.`,
        signal: AbortSignal.timeout(4000),
      });
    } catch (_) { /* never let telemetry or notification break intake */ }
  })();
  const rt = (globalThis as { EdgeRuntime?: { waitUntil?: (p: Promise<unknown>) => void } }).EdgeRuntime;
  if (rt?.waitUntil) rt.waitUntil(notify);

  return done(new Response(JSON.stringify({
    ok: true,
    jobId,
    portalCode: inserted?.portal_code || null
  }), { status: 200, headers: { ...CORS, "Content-Type": "application/json" } }), 200);
});
