import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { Trace, SpanKind, httpAttrs } from "./otel.ts";
import { pickTextProvider, providerAttrs, chatWithFailover, answerText, firstJsonObject, NO_PROVIDER_MESSAGE } from "./textmodel.ts";
import { NO_VISION_PROVIDER_MESSAGE, pickVisionProvider, visionAttrs } from "./visionmodel.ts";
import { scrub } from "./measurements.ts";

// yaad-sketch
//
// The Site Sketch Pack. A walkthrough video and a set of photos become an
// indicative record of a property: key frames, a room by room condition
// schedule, and a schematic sketch showing rooms, doors and where each photo
// was taken.
//
// THE LINE THIS FUNCTION DOES NOT CROSS.
// It does not measure anything. A phone video carries no scale, so any
// dimension taken from it would be invented, and producing measured drawings
// for reward is regulated work in Jamaica. So: the model is told it has no
// permission to state a dimension, the scrubber in _shared/measurements.ts
// removes any that appear anyway and reports them to the desk rather than
// hiding them, and has_measurement() in Postgres refuses to let a pack carrying
// one be approved. Three layers, one rule, and the rule is written once.
//
// The drawing is generated by code, not by the model. The model supplies the
// room list and which rooms connect. Where the boxes land on the page is a
// deterministic layout, which is why it is honest to call it a schematic: it
// shows topology, never geometry.
//
// WHY FRAMES ARRIVE ALREADY EXTRACTED.
// There is no ffmpeg in the edge runtime. Frames are pulled from the video in
// the browser with a <video> element and a canvas, which means the video never
// leaves her machine. Only the frames she chooses are ever uploaded. That is
// the better privacy answer as well as the only workable one.
//
// Actions, in the order the desk calls them:
//   frames    one batch of stills, described by the vision model
//   assemble  all batches, turned into rooms, a sketch and a stored draft
//   render    a pack, turned into the document a client reads

// nvidia/nemotron-nano-12b-v2-vl reached end of life on 26 Aug 2026 and now
// returns HTTP 410. Verified working replacement, checked against a real still
// on the day: it described the shot correctly and refused to call a phone in
// somebody's hand a room, which is the behaviour that matters here.
// Which vision model, and the endpoint it lives on, now come from
// _shared/visionmodel.ts, the same way the text model comes from
// _shared/textmodel.ts. Set NVIDIA_SKETCH_MODEL to move this job on its own,
// or NVIDIA_VISION_MODEL to move every vision job together as before.
//
// Named here for the record the assemble step writes. The frames were
// described in an earlier request, so this repeats that request's resolution
// rather than making a second decision.
const sketchVisionModel = () => pickVisionProvider("sketch")?.model ?? "not configured";

const FRAME_PROMPT = `You are looking at stills taken from a walkthrough video of a property in Jamaica, in the order they were filmed. You are recording what is visibly there, for a project manager who will read it later. You are not a surveyor, an engineer or a valuer.

You will be given several images, numbered. For EACH image, return one object.

Return STRICT JSON only, no markdown fences, exactly this shape:
{"frames":[{"n":1,"room":"plain name for the room or area, e.g. Front bedroom, Kitchen, Rear veranda, Roof","room_confidence":"high|medium|low","same_room_as_previous":true,"visible":"one sentence on what the shot actually shows","doors_to":["names of other rooms or outside that are visibly reachable from here"],"observations":[{"note":"one sentence, only what is visible","category":"cosmetic|maintenance|safety|structural|scope_mismatch","severity":"low|medium|high","recommend_professional":false}]}]}

Rules, all absolute:
1. You may NEVER state a dimension, a distance, an area, a height or a scale. Not in metres, feet, inches, or any other unit. Not even approximately, not even hedged. If size genuinely matters, describe it in words instead: "a hairline crack", "a full height crack", "a small patch", "most of the ceiling". There is no unit of measurement anywhere in your output.
2. Report only what is visible in that image. Never infer a room you cannot see.
3. Never state a structural or safety conclusion with certainty. Use "appears to", "worth checking in person". Anything in the structural or safety category must have recommend_professional set to true.
4. If a shot is too dark, too blurred or too close to judge, say exactly that as the "visible" text and return an empty observations array.
5. Consecutive frames are usually the same room. Set same_room_as_previous honestly, because it is what stitches the walkthrough together.
6. Never name a person, never read out a house number, never transcribe a document or a screen.
7. Do not describe furniture or possessions unless they are the point of the observation.`;

const ASSEMBLE_PROMPT = `You are assembling a walkthrough of a property in Jamaica into a room by room record. You are given, in filming order, what a vision model saw in each still. Your job is to merge duplicates into one room per real room, put them in a sensible order, and say which rooms connect.

Return STRICT JSON only, no markdown fences, exactly this shape:
{"property_summary":"two or three plain sentences describing the property as walked, no opinions on value or price","rooms":[{"key":"short-kebab-key","name":"Front bedroom","level":"ground|upper|outside|roof","walk_order":1,"frames":[1,2],"connects":["hallway"],"observations":[{"note":"","category":"cosmetic|maintenance|safety|structural|scope_mismatch","severity":"low|medium|high","recommend_professional":false}]}],"gaps":["what a reader should know was not filmed or not visible"]}

Rules, all absolute:
1. NEVER state a dimension, distance, area, height or scale, in any unit, anywhere, not even approximately. Describe size in words if it matters.
2. Every frame number you were given must appear in exactly one room's frames array. Do not drop one and do not use one twice.
3. "connects" holds keys of other rooms in your own list, or the literal "outside". Only claim a connection the frames actually support.
4. Merge observations that are plainly the same thing seen twice. Keep the clearer wording. Do not invent new findings.
5. "gaps" is where you are honest about what is missing: a room never entered, a roof never seen, a dark shot. This section is the difference between a record and a sales document.
6. Never name a person and never state an address.
7. The "room" on each still was checked by the person who filmed the walkthrough and is FINAL. Use those names exactly as given. Stills that carry the same room name are the same room: never split one name into two rooms, never rename one, and never add a room no still names. If every still names the same room, return exactly one room.`;

// The measurement rule and the scrubber now live in _shared/measurements.ts,
// with the case list that proves them and a test that fails if the Postgres
// copy has drifted from this one. It used to be typed out here, and again in
// yaad-report, and again in the migration: three hand-kept copies of one rule,
// which is how all three ended up letting "a 2-metre crack" through together.
// Moved 5 September 2026.

function bearer(req: Request): string {
  return (req.headers.get("authorization") || "").replace(/^Bearer\s+/i, "");
}
function claim(req: Request, key: string): string {
  try {
    return JSON.parse(atob(bearer(req).split(".")[1].replace(/-/g, "+").replace(/_/g, "/")))[key] || "";
  } catch (_) { return ""; }
}
async function db(req: Request, path: string, init: RequestInit = {}) {
  return await fetch(`${Deno.env.get("SUPABASE_URL")}/rest/v1/${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      apikey: Deno.env.get("SUPABASE_ANON_KEY")!,
      Authorization: `Bearer ${bearer(req)}`,
      ...(init.headers || {}),
    },
  });
}
async function isAdmin(req: Request): Promise<boolean> {
  try {
    const r = await db(req, "rpc/is_admin", { method: "POST", body: "{}" });
    return r.ok && (await r.json()) === true;
  } catch (_) { return false; }
}
const esc = (s: unknown) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));

// --------------------------------------------------------------- the sketch
//
// Rooms are laid out on a snaking grid in walk order, so two rooms visited one
// after the other end up next to each other on the page. Where a connection
// exists between grid neighbours it is drawn as a real gap in the shared wall
// with a door swing. Where it does not, it is a dashed line, which is the
// honest way to say "these connect, but not like this".
//
// There is not a single number on this drawing other than photo markers, and
// those are labelled as photos so they cannot be mistaken for dimensions.

type Room = {
  key: string; name: string; level?: string; walk_order?: number;
  frames?: number[]; connects?: string[];
  observations?: { note: string; category: string; severity: string; recommend_professional?: boolean }[];
};

function buildSketch(rooms: Room[]): string {
  const W = 168, H = 116, GAP = 40, PAD = 34;
  const n = rooms.length;
  if (!n) return "";
  const cols = Math.max(1, Math.min(4, Math.ceil(Math.sqrt(n))));
  const rowCount = Math.ceil(n / cols);

  const pos = new Map<string, { x: number; y: number; col: number; row: number }>();
  rooms.forEach((r, i) => {
    const row = Math.floor(i / cols);
    // Snake, so the walk reads left to right then right to left.
    const col = row % 2 === 0 ? i % cols : cols - 1 - (i % cols);
    pos.set(r.key, { x: PAD + col * (W + GAP), y: PAD + row * (H + GAP), col, row });
  });

  // The stamp at the foot is the most important text on this drawing, so the
  // canvas is never allowed to be narrower than the stamp needs. A cut-off
  // disclaimer is worse than no disclaimer.
  const width = Math.max(660, PAD * 2 + cols * W + (cols - 1) * GAP);
  const height = PAD * 2 + rowCount * H + (rowCount - 1) * GAP + 84;

  const parts: string[] = [];

  // Connections first, so rooms draw on top of them.
  const drawn = new Set<string>();
  for (const r of rooms) {
    for (const c of r.connects || []) {
      if (c === "outside") continue;
      const pair = [r.key, c].sort().join("|");
      if (drawn.has(pair)) continue;
      const a = pos.get(r.key), b = pos.get(c);
      if (!a || !b) continue;
      drawn.add(pair);

      const sameRow = a.row === b.row && Math.abs(a.col - b.col) === 1;
      const sameCol = a.col === b.col && Math.abs(a.row - b.row) === 1;

      if (sameRow) {
        const x = Math.max(a.x, b.x);          // left edge of the right-hand room
        const y = a.y + H / 2;
        parts.push(`<rect x="${x - GAP - 1}" y="${y - 17}" width="${GAP + 2}" height="34" fill="#fff"/>`);
        parts.push(`<path d="M ${x - GAP} ${y - 17} A 34 34 0 0 1 ${x} ${y + 17}" fill="none" stroke="#B7C9C3" stroke-width="1.4"/>`);
      } else if (sameCol) {
        const y = Math.max(a.y, b.y);
        const x = a.x + W / 2;
        parts.push(`<rect x="${x - 17}" y="${y - GAP - 1}" width="34" height="${GAP + 2}" fill="#fff"/>`);
        parts.push(`<path d="M ${x - 17} ${y - GAP} A 34 34 0 0 0 ${x + 17} ${y}" fill="none" stroke="#B7C9C3" stroke-width="1.4"/>`);
      } else {
        parts.push(`<line x1="${a.x + W / 2}" y1="${a.y + H / 2}" x2="${b.x + W / 2}" y2="${b.y + H / 2}" stroke="#C6D6D1" stroke-width="1.4" stroke-dasharray="5 5"/>`);
      }
    }
  }

  rooms.forEach((r) => {
    const p = pos.get(r.key)!;
    const outside = (r.connects || []).includes("outside");
    parts.push(`<rect x="${p.x}" y="${p.y}" width="${W}" height="${H}" fill="#FBFDFC" stroke="#0F1B17" stroke-width="2" rx="3"/>`);
    if (outside) {
      parts.push(`<rect x="${p.x + W / 2 - 17}" y="${p.y + H - 2}" width="34" height="4" fill="#fff"/>`);
      parts.push(`<text x="${p.x + W / 2}" y="${p.y + H + 17}" text-anchor="middle" font-size="10" fill="#67807A" font-family="'Space Grotesk',sans-serif">outside</text>`);
    }
    const name = esc(r.name).slice(0, 26);
    parts.push(`<text x="${p.x + 12}" y="${p.y + 24}" font-size="13" font-weight="700" fill="#0F1B17" font-family="'Space Grotesk',sans-serif">${name}</text>`);
    if (r.level && r.level !== "ground") {
      parts.push(`<text x="${p.x + 12}" y="${p.y + 40}" font-size="10" fill="#67807A" font-family="'Space Grotesk',sans-serif">${esc(r.level)}</text>`);
    }
    (r.frames || []).slice(0, 8).forEach((f, i) => {
      const cx = p.x + 22 + (i % 4) * 30, cy = p.y + H - 34 + Math.floor(i / 4) * 26;
      parts.push(`<circle cx="${cx}" cy="${cy}" r="11" fill="#14B8A6"/>`);
      parts.push(`<text x="${cx}" y="${cy + 4}" text-anchor="middle" font-size="10" font-weight="700" fill="#04120F" font-family="'Space Grotesk',sans-serif">${f}</text>`);
    });
  });

  const legendY = PAD + rowCount * H + (rowCount - 1) * GAP + 42;
  parts.push(`<circle cx="${PAD + 11}" cy="${legendY - 4}" r="11" fill="#14B8A6"/>`);
  parts.push(`<text x="${PAD + 11}" y="${legendY}" text-anchor="middle" font-size="10" font-weight="700" fill="#04120F" font-family="'Space Grotesk',sans-serif">n</text>`);
  parts.push(`<text x="${PAD + 30}" y="${legendY}" font-size="11" fill="#4A5F5A" font-family="'Space Grotesk',sans-serif">where photo n was taken</text>`);
  // Two short lines rather than one long one, so it fits at any room count.
  parts.push(`<text x="${PAD}" y="${legendY + 22}" font-size="11" fill="#8A5A00" font-family="'Space Grotesk',sans-serif">Schematic only. Rooms are drawn the same size whatever their real size.</text>`);
  parts.push(`<text x="${PAD}" y="${legendY + 37}" font-size="11" fill="#8A5A00" font-family="'Space Grotesk',sans-serif">Nothing here is to scale and nothing has been measured.</text>`);

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="100%" role="img" aria-label="Schematic sketch of the rooms walked, not to scale">
<rect width="${width}" height="${height}" fill="#fff"/>
${parts.join("\n")}
</svg>`;
}

// --------------------------------------------------------------- pack render

// ── The map ────────────────────────────────────────────────────────────────
//
// Two ways to get one, and the keyless one is the default. Both send the
// property address to a third party, which is why docs/privacy.html names
// them both and why the address column was a founder decision on 6 September
// 2026. Neither is ever called by the client's browser: the image is fetched
// here, once, and stored on the pack.

const MAP_AGENT = "YaadlyHub/1.0 (site inspection reports; hello@yaadly.co.uk)";

/**
 * A stored map is a data URI this function made, and nothing else.
 *
 * SVG is on the list because the OpenStreetMap map is assembled as one. An
 * SVG loaded through an <img> cannot run script, which is what makes that
 * safe; do not lift this into an inline <svg> without reading safeSvg in the
 * desk first.
 */
function isMapImage(s: unknown): boolean {
  return /^data:image\/(png|jpeg|jpg|gif|webp|svg\+xml);base64,[A-Za-z0-9+/=]+$/.test(String(s || ""));
}

function toDataUri(bytes: Uint8Array, type: string): string {
  let bin = "";
  for (let i = 0; i < bytes.length; i += 0x8000) bin += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  return `data:${type};base64,${btoa(bin)}`;
}

/** Google Static Maps. Better imagery, needs a key with billing behind it. */
async function googleMap(address: string, key: string, trace: Trace): Promise<string | null> {
  const q = new URLSearchParams({
    center: address, zoom: "19", size: "640x400", scale: "2", maptype: "hybrid",
    markers: `color:red|${address}`, key,
  });
  return await trace.span("google static map", SpanKind.CLIENT, { "server.address": "maps.googleapis.com", "yaadly.model.region": "us" }, async (s) => {
    const r = await fetch(`https://maps.googleapis.com/maps/api/staticmap?${q}`, { signal: AbortSignal.timeout(20_000) });
    s.setAttributes({ "http.response.status_code": r.status });
    if (!r.ok) { console.error(`yaad-sketch map: google http ${r.status}: ${(await r.text().catch(() => "")).slice(0, 200)}`); return null; }
    return toDataUri(new Uint8Array(await r.arrayBuffer()), r.headers.get("content-type") || "image/png");
  });
}

/**
 * OpenStreetMap, with no key and no account.
 *
 * Nominatim turns the address into a point, then a three by three grid of map
 * tiles is fetched and assembled into one SVG with the tiles embedded and a
 * marker drawn on the point. Assembled as SVG because there is no canvas in
 * the edge runtime to paste raster tiles together with, and an SVG in an
 * <img> cannot run scripts, so it is safe to store and print. Both services
 * are the OpenStreetMap Foundation's, in the EU, and both ask for a real
 * User-Agent, which MAP_AGENT is. A handful of tiles per report is well
 * inside their acceptable use.
 */
async function osmMap(address: string, trace: Trace): Promise<string | null> {
  return await trace.span("openstreetmap", SpanKind.CLIENT, { "server.address": "nominatim.openstreetmap.org", "yaadly.model.region": "eu" }, async (s) => {
    const g = await fetch(`https://nominatim.openstreetmap.org/search?${new URLSearchParams({ q: address, format: "json", limit: "1" })}`,
      { headers: { "User-Agent": MAP_AGENT, "Accept-Language": "en" }, signal: AbortSignal.timeout(20_000) });
    s.setAttributes({ "http.response.status_code": g.status });
    if (!g.ok) { console.error(`yaad-sketch map: nominatim http ${g.status}`); return null; }
    const hits = await g.json().catch(() => []);
    if (!Array.isArray(hits) || !hits.length) { console.error(`yaad-sketch map: nominatim found nothing for "${address.slice(0, 80)}"`); return null; }
    const lat = Number(hits[0].lat), lon = Number(hits[0].lon);
    if (!Number.isFinite(lat) || !Number.isFinite(lon)) return null;

    const Z = 18, N = 2 ** Z, T = 256;
    const px = (lon + 180) / 360 * N * T;
    const rad = lat * Math.PI / 180;
    const py = (1 - Math.asinh(Math.tan(rad)) / Math.PI) / 2 * N * T;
    const x0 = Math.floor(px / T) - 1, y0 = Math.floor(py / T) - 1;

    const tiles = await Promise.all([0, 1, 2].flatMap((dy) => [0, 1, 2].map(async (dx) => {
      const x = x0 + dx, y = y0 + dy;
      if (x < 0 || y < 0 || x >= N || y >= N) return null;
      const r = await fetch(`https://tile.openstreetmap.org/${Z}/${x}/${y}.png`,
        { headers: { "User-Agent": MAP_AGENT }, signal: AbortSignal.timeout(15_000) });
      if (!r.ok) return null;
      return { dx, dy, uri: toDataUri(new Uint8Array(await r.arrayBuffer()), "image/png") };
    })));
    const got = tiles.filter(Boolean) as { dx: number; dy: number; uri: string }[];
    if (!got.length) { console.error("yaad-sketch map: no OpenStreetMap tiles came back"); return null; }

    // Where the property sits inside the assembled 768 by 768 grid, then a
    // 640 by 400 window centred on it.
    const mx = px - x0 * T, my = py - y0 * T;
    const vx = Math.round(mx - 320), vy = Math.round(my - 200);
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="640" height="400" viewBox="${vx} ${vy} 640 400">`
      + got.map(t => `<image x="${t.dx * T}" y="${t.dy * T}" width="${T}" height="${T}" xlink:href="${t.uri}"/>`).join("")
      + `<g transform="translate(${mx.toFixed(1)},${my.toFixed(1)})">`
      + `<circle r="11" fill="#B42318" fill-opacity="0.25"/><circle r="6" fill="#B42318" stroke="#fff" stroke-width="2.5"/></g>`
      + `<text x="${vx + 8}" y="${vy + 392}" font-family="sans-serif" font-size="11" fill="#333">Map data from OpenStreetMap contributors</text>`
      + `</svg>`;
    s.setAttributes({ "yaadly.sketch.map_tiles": got.length });
    return `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`;
  });
}

function renderPack(p: Record<string, any>, stamp: string): string {
  const rooms: Room[] = p.rooms || [];
  const frames: any[] = p.frames || [];
  const sev = (s: string) => ({ high: "#B42318", medium: "#8A5A00", low: "#4A5F5A" }[s] || "#4A5F5A");
  const escalating = rooms.flatMap(r => r.observations || []).filter(o => o.recommend_professional || o.category === "structural" || o.category === "safety");
  // What the person typed, one line per point.
  const notes: string[] = String(p.visit_notes || "").split("\n").map((s: string) => s.replace(/^[-*•]\s*/, "").trim()).filter(Boolean).slice(0, 40);

  // The photographic schedule: every still in walk order, grouped under its
  // room, the picture on the left and what was seen on the right. The shape
  // Monique asked for on 6 September 2026, from a surveyor's condition
  // schedule she uses as the reference. Stills without a stored image (packs
  // built before that day) get a numbered placeholder rather than a gap.
  const isImg = (s: unknown) => /^data:image\/(png|jpeg|jpg|gif|webp);base64,[A-Za-z0-9+/=]+$/.test(String(s || ""));
  const byN = new Map<number, any>(frames.map((f: any) => [Number(f.n), f]));
  const placed = new Set<number>();
  const photoRow = (n: number) => {
    const f = byN.get(n); placed.add(n);
    const obs: any[] = (f?.observations || []);
    return `<tr>
      <td class="ph"><div class="num">${n}.</div>${f && isImg(f.image) ? `<img src="${f.image}" alt="Photograph ${n}">` : `<div class="noimg">Photograph ${n}: image not stored with this report.</div>`}</td>
      <td class="ds">${f?.caption ? `<p>${esc(f.caption)}</p>` : ""}${obs.length ? obs.map((o: any) => `<p><b>${esc(String(o.category || "").replace("_", " "))}, ${esc(o.severity || "")}.</b> ${esc(o.note || "")}${o.recommend_professional ? ' <em class="pro">Worth a qualified person looking at this in person.</em>' : ""}</p>`).join("") : (f?.caption ? "" : `<p class="none">Nothing recorded for this photograph.</p>`)}</td>
    </tr>`;
  };
  const photoRows = rooms.map((r) => {
    const ns = (r.frames || []).map((n: any) => Number(n)).filter((n: number) => byN.has(n));
    if (!ns.length) return "";
    return `<tr class="rh"><td colspan="2">${esc(r.name)}${r.level && r.level !== "ground" ? `, ${esc(r.level)}` : ""}</td></tr>` + ns.map(photoRow).join("");
  }).join("");
  const unplaced = frames.map((f: any) => Number(f.n)).filter((n: number) => !placed.has(n)).sort((a: number, b: number) => a - b);
  const photoTable = `<table class="photos"><thead><tr><th>Photographs</th><th>Descriptions</th></tr></thead><tbody>${photoRows}${unplaced.length ? `<tr class="rh"><td colspan="2">Not placed in a room</td></tr>` + unplaced.map(photoRow).join("") : ""}</tbody></table>`;

  const roomBlocks = rooms.map((r) => `
    <section class="room">
      <h3>${esc(r.name)}${r.level && r.level !== "ground" ? ` <span class="lvl">${esc(r.level)}</span>` : ""}</h3>
      <div class="shots">${(r.frames || []).map(f => `<span class="shot">photo ${f}</span>`).join("")}</div>
      ${(r.observations || []).length ? `<ul>${(r.observations || []).map(o => `
        <li><span class="dot" style="background:${sev(o.severity)}"></span>
        <b>${esc(o.category.replace("_", " "))}, ${esc(o.severity)}</b>. ${esc(o.note)}
        ${o.recommend_professional ? '<em class="pro">Worth a qualified person looking at this in person.</em>' : ""}</li>`).join("")}</ul>`
        : `<p class="none">Nothing notable visible in what was filmed here.</p>`}
    </section>`).join("");

  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(p.id)} Site Inspection Report</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Space+Grotesk:wght@400;500;700&display=swap" rel="stylesheet">
<style>
:root{--teal:#14B8A6;--deep:#08110F;--line:#DCE6E2;--mute:#5E7772}
*{box-sizing:border-box}
body{margin:0;padding:32px 20px;background:#F4F7F6;color:var(--deep);font:15px/1.6 'Space Grotesk',-apple-system,sans-serif}
.sheet{max-width:820px;margin:0 auto;background:#fff;padding:44px 48px;border-radius:14px;box-shadow:0 2px 24px rgba(8,17,15,.08)}
header{border-bottom:3px solid var(--teal);padding-bottom:20px;display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}
.mark{font-family:'Anton',Impact,sans-serif;font-size:32px;line-height:1}.mark span{color:var(--teal)}
h1{font-family:'Anton',Impact,sans-serif;font-weight:400;font-size:26px;margin:0;letter-spacing:.6px}
.ref{font-size:15px;font-weight:700;color:var(--mute)}
.stamp{margin:22px 0;padding:15px 18px;background:#FFFBF2;border:1px solid #FFE0A3;border-radius:9px;color:#8A5A00;font-size:13.5px}
.meta{display:flex;gap:30px;flex-wrap:wrap;margin:22px 0}
.meta h2{font-size:10px;letter-spacing:1.4px;text-transform:uppercase;color:var(--mute);margin:0 0 4px}
.meta p{margin:0}
h2.sec{font-family:'Anton',Impact,sans-serif;font-weight:400;font-size:19px;letter-spacing:.7px;margin:34px 0 12px;padding-top:18px;border-top:1px solid var(--line)}
.summary{font-size:16px}
.sketch{border:1px solid var(--line);border-radius:10px;padding:14px;background:#fff;overflow-x:auto}
.room{padding:16px 0;border-bottom:1px solid var(--line)}
.room h3{margin:0 0 6px;font-size:16px}
.lvl{font-size:11px;color:var(--mute);font-weight:400;text-transform:uppercase;letter-spacing:1.1px}
.shots{margin-bottom:8px}
.shot{display:inline-block;background:#E8F6F4;color:#0B7A6E;border-radius:999px;padding:2px 10px;font-size:11px;font-weight:700;margin-right:6px}
.room ul{margin:0;padding:0;list-style:none}
.room li{padding:7px 0 7px 20px;position:relative;font-size:14.5px}
.dot{position:absolute;left:0;top:14px;width:9px;height:9px;border-radius:50%}
.pro{display:block;color:#B42318;font-style:normal;font-size:13px;margin-top:2px}
.none{color:var(--mute);font-size:14px;margin:0}
.gaps{background:#F4F7F6;border-left:3px solid var(--teal);padding:14px 18px;border-radius:0 9px 9px 0}
.gaps ul{margin:6px 0 0;padding-left:18px}
.esc{background:#FEF3F2;border:1px solid #FDA29B;border-radius:9px;padding:14px 18px;color:#B42318;font-size:14px}
footer{margin-top:34px;padding-top:18px;border-top:1px solid var(--line);font-size:12px;color:var(--mute);line-height:1.75}
.detail{display:grid;grid-template-columns:170px 1fr;gap:0;margin:22px 0 20px;border-top:1px solid var(--line)}
.detail dt{font-weight:700;font-size:13px;padding:8px 12px 8px 0;border-bottom:1px solid var(--line)}
.detail dd{margin:0;font-size:14px;padding:8px 0;border-bottom:1px solid var(--line)}
.scope p{margin:0 0 10px;font-size:14.5px}
ul.notes{margin:0 0 6px;padding-left:20px;font-size:14.5px}
ul.notes li{margin-bottom:5px}
.sign{width:100%;border-collapse:collapse;margin-top:6px}
.sign td{border:1px solid var(--line);padding:12px 14px;width:50%;vertical-align:top}
.sign b{display:block;font-size:10px;letter-spacing:1.2px;text-transform:uppercase;color:var(--mute);margin-bottom:8px}
.sign .who{display:block;font-size:17px;font-weight:700;padding-bottom:8px;border-bottom:1px solid var(--deep);margin-bottom:6px}
.sign .who.unsigned{color:#8A5A00;border-bottom-style:dashed;border-bottom-color:#FFE0A3;font-weight:400}
.sign .when{display:block;font-size:12px;color:var(--mute)}
.photos{width:100%;border-collapse:collapse;margin-top:6px}
.photos th{text-align:left;font-size:13px;padding:8px 10px;border:1px solid var(--line);background:#F4F7F6}
.photos td{border:1px solid var(--line);vertical-align:top;padding:10px}
.photos td.ph{width:46%}
.photos td.ph img{width:100%;display:block;border-radius:4px}
.photos .num{font-weight:700;margin-bottom:6px}
.photos .noimg{background:#F4F7F6;color:var(--mute);font-size:12px;padding:30px 12px;text-align:center;border-radius:4px}
.photos td.ds{font-size:13.5px;line-height:1.55}
.photos td.ds p{margin:0 0 8px}
.photos tr.rh td{background:#E8F6F4;font-weight:700;font-size:13px;padding:6px 10px}
.photos tr{page-break-inside:avoid}
h2.sec{page-break-after:avoid}
@media print{body{background:#fff;padding:0}.sheet{box-shadow:none;padding:0;max-width:none}}
</style></head><body><div class="sheet">
<header>
  <div><div class="mark">YAADLY<span>.</span></div><div class="ref">Site Inspection Report</div></div>
  <div style="text-align:right"><h1>${esc(p.property_label)}</h1><div class="ref">${esc(p.id)}${p.rev > 1 ? ` rev ${esc(p.rev)}` : ""}</div></div>
</header>

<dl class="detail">
  <dt>Report number</dt><dd>${esc(p.id)}${p.rev > 1 ? `, revision ${esc(p.rev)}` : ""}</dd>
  <dt>Date of visit</dt><dd>${esc(p.visit_date || "Not stated")}</dd>
  <dt>Property</dt><dd>${esc(p.property_label)}</dd>
  ${p.address ? `<dt>Site address</dt><dd>${esc(p.address)}${p.parish ? `, ${esc(p.parish)}` : ""}</dd>` : p.parish ? `<dt>Parish</dt><dd>${esc(p.parish)}</dd>` : ""}
  <dt>Prepared for</dt><dd>${esc(p.client_name || "Not stated")}</dd>
  ${p.job_ref ? `<dt>Job reference</dt><dd>${esc(p.job_ref)}</dd>` : ""}
  ${p.contractor ? `<dt>Contractor</dt><dd>${esc(p.contractor)}</dd>` : ""}
  <dt>Visit conducted by</dt><dd>${esc(p.captured_by || "Not stated")}</dd>
  <dt>Conditions</dt><dd>${esc(p.conditions || "Not recorded")}</dd>
  <dt>Photographs</dt><dd>${frames.length}, numbered and grouped by room</dd>
</dl>

<div class="scope">
  <p>This document records the visible condition of ${esc(p.property_label)} at the time of the visit. It contains a photographic record of the areas that were walked and filmed. Photographs are numbered, grouped by room, and shown against the drawing overview at the end of the report for orientation.</p>
  <p>It is a visual record only. No investigation has been made into the structure, the services or anything below the surface, and nothing in it has been measured. Where an item is marked as worth a qualified person seeing, that is a note that it is there, not a judgement of how serious it is.</p>
  ${p.property_summary ? `<p>${esc(p.property_summary)}</p>` : ""}
</div>

${notes.length ? `<h2 class="sec">Site condition on the day</h2>
<ul class="notes">${notes.map((l: string) => `<li>${esc(l)}</li>`).join("")}</ul>
<p class="none">In the words of the person who carried out the visit.</p>` : ""}

<div class="stamp"><b>Read this first.</b> ${esc(stamp)}</div>

${p.address && isMapImage(p.map_image) ? `<h2 class="sec">Location</h2>
<div class="sketch"><img src="${p.map_image}" alt="Map of the property" style="width:100%;display:block;border-radius:6px"><p class="none" style="margin-top:8px">${esc(p.address)}. ${String(p.map_image).startsWith("data:image/svg") ? "Map data from OpenStreetMap contributors." : "Map from Google."} Marker placed by address, not by survey.</p></div>` : ""}

<h2 class="sec">Photographs and descriptions</h2>
${photoTable}

${p.sketch_svg ? `<h2 class="sec">Drawing overview</h2><div class="sketch">${p.sketch_svg}</div><p class="none" style="margin-top:8px">Schematic only: the rooms that were walked, how they connect, and where each numbered photograph was taken. Not to scale, and no dimension on it has been measured.</p>` : ""}

<h2 class="sec">Findings by room</h2>
${roomBlocks || "<p class='none'>No rooms recorded.</p>"}

${escalating.length ? `<h2 class="sec">Worth a qualified person seeing</h2>
<div class="esc">${escalating.length} observation${escalating.length > 1 ? "s" : ""} in this pack fall${escalating.length > 1 ? "" : "s"} outside what can be judged from a photograph. They are marked in the schedule above. This pack does not tell you how serious they are, only that they are there.</div>` : ""}

${(p.gaps || []).length ? `<h2 class="sec">What this pack does not cover</h2>
<div class="gaps">Filmed on one visit, so it records only what was walked and lit at the time.<ul>${(p.gaps || []).map((g: string) => `<li>${esc(g)}</li>`).join("")}</ul></div>` : ""}

<h2 class="sec">Signed off</h2>
<table class="sign">
  <tr>
    <td><b>Visit conducted by</b><span class="who">${esc(p.captured_by || "Not stated")}</span><span class="when">${p.visit_date ? `On site ${esc(p.visit_date)}` : "Date not stated"}</span></td>
    <td><b>Checked and approved by</b>${p.approved_by
      ? `<span class="who">${esc(p.approved_by)}</span><span class="when">${esc(String(p.approved_at || "").slice(0, 16).replace("T", " "))}${p.issued_at ? `, issued ${esc(String(p.issued_at).slice(0, 10))}` : ""}</span>`
      : `<span class="who unsigned">Not yet approved</span><span class="when">This is a draft. Nobody has checked it.</span>`}</td>
  </tr>
</table>
<p class="none">Approval is recorded by the system at the moment a named, signed-in person approves the report. It cannot be typed in afterwards. Reopening the report for edits clears it and starts a new revision.</p>

<footer>
  Yaadly Ltd. ${esc(p.id)}. ${esc(p.property_label)}${p.client_name ? `. ${esc(p.client_name)}` : ""}. ${frames.length} photograph${frames.length === 1 ? "" : "s"}.<br>
  ${esc(stamp)}<br>
  Yaadly Ltd, registered in England and Wales, company number 17358077.<br>
  This document records observation and documentation only. It is not a survey, a structural report, a valuation, a legal opinion or a quantity surveyor's estimate, and nothing in it should be relied on as one. Findings reflect conditions visible on the day of filming.
</footer>
</div></body></html>`;
}

// --------------------------------------------------------------- handler

Deno.serve(async (req) => {
  const cors = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
  };
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });

  const trace = new Trace("yaad-sketch", req);
  const root = trace.startSpan("POST /yaad-sketch", SpanKind.SERVER, httpAttrs(req));
  const done = (body: BodyInit, status: number, ct = "application/json") => {
    root.setAttributes({ "http.response.status_code": status });
    root.end(); trace.flush();
    return new Response(body, { status, headers: { ...cors, "Content-Type": ct } });
  };
  const fail = (m: string, s: number) => done(JSON.stringify({ error: m }), s);

  try {
    if (claim(req, "role") !== "authenticated") {
      root.setAttributes({ "yaadly.auth.outcome": "rejected" });
      return fail("Sign in required.", 401);
    }
    if (!(await isAdmin(req))) {
      root.setAttributes({ "yaadly.auth.outcome": "not_admin" });
      return fail("Admin only.", 403);
    }
    root.setAttributes({ "yaadly.auth.outcome": "admin" });

    const body = await req.json().catch(() => ({}));
    const action = String(body.action || "");
    root.setAttributes({ "yaadly.sketch.action": action });

    // ------------------------------------------------------------- frames
    if (action === "frames") {
      const vprov = pickVisionProvider("sketch");
      if (!vprov) return fail(NO_VISION_PROVIDER_MESSAGE, 500);

      const images: string[] = Array.isArray(body.images) ? body.images.slice(0, 6) : [];
      const startAt = Number(body.start_at) || 1;
      if (!images.length) return fail("No frames in this batch.", 400);

      // The instructions travel INSIDE the user message, ahead of the images,
      // not as a separate system message. Llama 3.2 vision does not honour a
      // system prompt next to an image: on 6 September 2026 the 11b took the
      // system message and read it straight back as its answer, word for
      // word, and the desk showed "answered, but not in JSON". Same text,
      // different envelope, and the model follows it.
      const contentFor = (strict: boolean): Record<string, unknown>[] => {
        const c: Record<string, unknown>[] = [{
          type: "text",
          text: `${FRAME_PROMPT}\n\nThese are stills ${startAt} to ${startAt + images.length - 1} from the walkthrough, in filming order. Number them from ${startAt}. ${body.context ? "Context from the person who filmed it: " + String(body.context).slice(0, 400) : ""}`
            + `\n\nReply with ONLY the JSON object, starting with { and ending with }. No words before it, no words after it, no bullet points.`
            + (strict ? `\n\nYour previous answer was not valid JSON. This time return nothing but the JSON object.` : ""),
        }];
        for (const img of images) c.push({ type: "image_url", image_url: { url: img } });
        return c;
      };

      // The first { to the last }, then parse. The 11b sometimes writes a
      // sentence before the object and sometimes a sentence after it, and a
      // greedy match on the braces takes both in its stride. Null when there
      // is no usable object, so the caller can ask once more.
      const parseFrames = (text: string): any | null => {
        const s = String(text);
        const a = s.indexOf("{"), b = s.lastIndexOf("}");
        if (a < 0 || b <= a) return null;
        try {
          const p = JSON.parse(s.slice(a, b + 1));
          return Array.isArray(p?.frames) && p.frames.length ? p : null;
        } catch (_) { return null; }
      };

      const describe = (strict: boolean) => trace.span(`chat ${vprov.model}${strict ? " strict" : ""}`, SpanKind.CLIENT, {
        ...visionAttrs(vprov),
        "gen_ai.request.temperature": 0.2,
        "yaadly.sketch.batch_size": images.length,
      }, async (s) => {
        // A deadline, and one more go. Until 6 September 2026 this fetch had
        // no timeout at all. NVIDIA's hosted endpoint sometimes takes a
        // request and never answers it (see _shared/visionmodel.ts), and the
        // desk's first real walkthrough hit exactly that: the function sat on
        // the open connection until the platform killed it, a 504 and then a
        // 546 in the edge log and not one line from this code, because this
        // code never got control back. Forty seconds, then once more, fits
        // twice inside the platform's own limit with room to answer.
        const ask = () => fetch(vprov.api, {
          method: "POST",
          headers: { Authorization: `Bearer ${vprov.key}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            model: vprov.model,
            messages: [{ role: "user", content: contentFor(strict) }],
            max_tokens: 1800, temperature: strict ? 0 : 0.2,
          }),
          signal: AbortSignal.timeout(40_000),
        });
        let r: Response;
        try {
          r = await ask();
          if (r.status >= 500) { try { await r.text(); } catch (_) { /* discarded */ } console.error(`yaad-sketch frame: nvidia http ${r.status}, trying once more`); r = await ask(); }
        } catch (e) {
          console.error(`yaad-sketch frame: nvidia gave no answer in 40s (${String(e).slice(0, 80)}), trying once more`);
          r = await ask();
        }
        const body = await r.text();
        let j: any = {};
        try { j = JSON.parse(body); } catch (_) { /* keep the raw text */ }
        s.setAttributes({
          "http.response.status_code": r.status,
          "gen_ai.usage.input_tokens": j?.usage?.prompt_tokens,
          "gen_ai.usage.output_tokens": j?.usage?.completion_tokens,
        });
        if (!r.ok) {
          const msg = `yaad-sketch frame: nvidia http ${r.status}: ${body.slice(0, 200)}`;
          s.recordError(msg); console.error(msg);
        }
        // A failed model call must never come back looking like "the model saw
        // nothing". That reads as a clean result and it is not one.
        return { ok: r.ok, status: r.status, body, content: j?.choices?.[0]?.message?.content ?? "" };
      });

      let raw = await describe(false);
      let parsed: any = raw.ok ? parseFrames(raw.content) : null;
      if (raw.ok && !parsed && String(raw.content).trim()) {
        // Answered, but not as JSON. One more go, told plainly what went
        // wrong, at temperature zero. Cheap on the 11b and it usually lands.
        console.error(`yaad-sketch frame: ${vprov.model} answered but not in JSON, asking once more strictly: ${String(raw.content).slice(0, 160)}`);
        raw = await describe(true);
        parsed = raw.ok ? parseFrames(raw.content) : null;
      }

      if (!raw.ok) {
        root.setAttributes({ "yaadly.sketch.outcome": "model_error" });
        return fail(`The vision model refused the request (HTTP ${raw.status}). It said: ${raw.body.slice(0, 300)}`, 502);
      }
      // Each of the three failures below is logged as well as returned, since
      // 6 September 2026. Before that a model that answered in prose instead
      // of JSON left nothing in function_logs at all: the desk got the message
      // and the log looked like a clean run, which is the worst combination.
      if (!String(raw.content).trim()) {
        root.setAttributes({ "yaadly.sketch.outcome": "empty_response" });
        console.error(`yaad-sketch frame: ${vprov.model} returned an empty answer: ${raw.body.slice(0, 300)}`);
        return fail(`The vision model returned an empty answer. Raw response: ${raw.body.slice(0, 300)}`, 502);
      }

      if (!parsed) {
        root.setAttributes({ "yaadly.sketch.outcome": "unparseable" });
        console.error(`yaad-sketch frame: ${vprov.model} answered but not in JSON, twice: ${String(raw.content).slice(0, 300)}`);
        return fail(`The vision model answered, but not in JSON, twice. It said: ${String(raw.content).slice(0, 300)}`, 502);
      }
      console.error(`yaad-sketch frame: ${vprov.model} described ${parsed.frames.length} still(s) from ${startAt}`);

      const hits: string[] = [];
      const out = (parsed.frames || []).map((f: any, i: number) => ({
        n: Number(f.n) || startAt + i,
        room: scrub(f.room, hits).slice(0, 60),
        room_confidence: ["high", "medium", "low"].includes(f.room_confidence) ? f.room_confidence : "low",
        same_room_as_previous: f.same_room_as_previous === true,
        visible: scrub(f.visible, hits).slice(0, 300),
        doors_to: Array.isArray(f.doors_to) ? f.doors_to.map((d: any) => String(d).slice(0, 40)).slice(0, 6) : [],
        observations: (Array.isArray(f.observations) ? f.observations : []).slice(0, 8).map((o: any) => ({
          note: scrub(o.note, hits).slice(0, 260),
          category: ["cosmetic", "maintenance", "safety", "structural", "scope_mismatch"].includes(o.category) ? o.category : "maintenance",
          severity: ["low", "medium", "high"].includes(o.severity) ? o.severity : "low",
          recommend_professional: o.recommend_professional === true || o.category === "safety" || o.category === "structural",
        })),
      }));

      root.setAttributes({ "yaadly.sketch.frames_described": out.length, "yaadly.sketch.measurement_scrubs": hits.length });
      return done(JSON.stringify({ frames: out, scrubbed: hits }), 200);
    }

    // ----------------------------------------------------------- assemble
    if (action === "assemble") {
      const prov = pickTextProvider();
      if (!prov) return fail(NO_PROVIDER_MESSAGE, 500);
      const described: any[] = Array.isArray(body.frames) ? body.frames : [];
      if (!described.length) return fail("Nothing to assemble: describe the frames first.", 400);

      // A desk call: the person building the pack can wait for it. Two retries
      // with Retry-After honoured up to fifteen seconds, then the failover in
      // chatWithFailover if a fallback provider is configured. Until
      // 6 September 2026 this was a bare fetch and one 429 meant no pack.
      // max_tokens is set high on purpose: MiniMax reasons in a <think> block
      // before it answers, and with the provider's default budget the thinking
      // used the room up and the JSON never arrived. answerText() strips the
      // thinking; the budget makes sure there is an answer after it.
      const assembleOnce = (strict: boolean) => trace.span(`chat ${prov.model}${strict ? " strict" : ""}`, SpanKind.CLIENT, {
        ...providerAttrs(prov),
        "gen_ai.operation.name": "chat",
        "gen_ai.request.temperature": strict ? 0 : 0.1,
      }, async (s) => {
        const { provider, res: r } = await chatWithFailover(prov, {
          temperature: strict ? 0 : 0.1,
          max_tokens: 6000,
          messages: [
            { role: "system", content: ASSEMBLE_PROMPT },
            { role: "user", content: JSON.stringify({ property: String(body.property_label || ""), frames: described }).slice(0, 24000)
              + (strict ? "\n\nYour previous answer was not valid JSON. Return ONLY the JSON object, starting with { and ending with }. No reasoning, no words before or after it." : "") },
          ],
        }, { timeoutMs: 60_000, retries: 2, maxRetryWaitMs: 15_000 });
        // Named rawText, not body: the request payload is already called `body`
        // in this scope, and shadowing it here put the reference on the line
        // above into the temporal dead zone. That threw a ReferenceError every
        // time assemble ran, before the model was ever called.
        const rawText = await r.text();
        let j: any = {};
        try { j = JSON.parse(rawText); } catch (_) { /* keep the raw text */ }
        s.setAttributes({
          ...providerAttrs(provider),
          "http.response.status_code": r.status,
          "gen_ai.usage.input_tokens": j?.usage?.prompt_tokens,
          "gen_ai.usage.output_tokens": j?.usage?.completion_tokens,
        });
        if (!r.ok) {
          const msg = `yaad-sketch assemble: ${provider.name} http ${r.status}: ${rawText.slice(0, 200)}`;
          s.recordError(msg); console.error(msg);
        }
        return { ok: r.ok, status: r.status, body: rawText, content: j?.choices?.[0]?.message?.content ?? "" };
      });

      let raw = await assembleOnce(false);
      let parsed: any = raw.ok ? firstJsonObject(raw.content) : null;
      if (raw.ok && !parsed && answerText(raw.content)) {
        console.error(`yaad-sketch assemble: ${prov.model} answered but not in JSON, asking once more strictly: ${answerText(raw.content).slice(0, 160)}`);
        raw = await assembleOnce(true);
        parsed = raw.ok ? firstJsonObject(raw.content) : null;
      }

      if (!raw.ok) return fail(`The assembly model refused the request (HTTP ${raw.status}). It said: ${raw.body.slice(0, 300)}`, 502);
      if (!answerText(raw.content)) return fail(`The assembly model returned an empty answer. Raw response: ${raw.body.slice(0, 300)}`, 502);
      if (!parsed) {
        console.error(`yaad-sketch assemble: ${prov.model} answered but not in JSON, twice: ${answerText(raw.content).slice(0, 300)}`);
        return fail(`The assembly model answered, but not in JSON, twice. It said: ${answerText(raw.content).slice(0, 300)}`, 502);
      }

      const hits: string[] = [];
      const seenKeys = new Set<string>();
      const rooms: Room[] = (Array.isArray(parsed.rooms) ? parsed.rooms : []).slice(0, 30).map((r: any, i: number) => {
        let k = String(r.key || r.name || `room-${i + 1}`).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40) || `room-${i + 1}`;
        while (seenKeys.has(k)) k = k + "-2";
        seenKeys.add(k);
        return {
          key: k,
          name: scrub(r.name, hits).slice(0, 60) || `Room ${i + 1}`,
          level: ["ground", "upper", "outside", "roof"].includes(r.level) ? r.level : "ground",
          walk_order: Number(r.walk_order) || i + 1,
          frames: (Array.isArray(r.frames) ? r.frames : []).map((f: any) => Number(f)).filter((f: number) => Number.isFinite(f)),
          connects: (Array.isArray(r.connects) ? r.connects : []).map((c: any) => String(c).toLowerCase().replace(/[^a-z0-9]+/g, "-")).slice(0, 8),
          observations: (Array.isArray(r.observations) ? r.observations : []).slice(0, 12).map((o: any) => ({
            note: scrub(o.note, hits).slice(0, 260),
            category: ["cosmetic", "maintenance", "safety", "structural", "scope_mismatch"].includes(o.category) ? o.category : "maintenance",
            severity: ["low", "medium", "high"].includes(o.severity) ? o.severity : "low",
            recommend_professional: o.recommend_professional === true || o.category === "safety" || o.category === "structural",
          })),
        };
      });

      if (!rooms.length) return fail("The assembly step found no rooms in those frames.", 422);
      rooms.sort((a, b) => (a.walk_order || 0) - (b.walk_order || 0));

      // The person's room names win over the model's grouping, in code and not
      // only in the prompt. Added 6 September 2026 after a seven second video
      // of one bedroom came back as two rooms. Two rules:
      //   a. two rooms with the same name are one room, merged;
      //   b. if every still names the same room, the pack has exactly one
      //      room, whatever the model decided.
      const sameName = (a: string, b: string) => a.trim().toLowerCase() === b.trim().toLowerCase();
      const merged: Room[] = [];
      for (const r of rooms) {
        const into = merged.find(m => sameName(m.name, r.name));
        if (!into) { merged.push(r); continue; }
        into.frames = [...(into.frames || []), ...(r.frames || [])];
        into.connects = [...new Set([...(into.connects || []), ...(r.connects || [])])].filter(c => c !== into.key && c !== r.key);
        into.observations = [...(into.observations || []), ...(r.observations || [])].slice(0, 12);
        for (const other of merged) other.connects = (other.connects || []).map(c => c === r.key ? into.key : c);
      }
      rooms.length = 0; rooms.push(...merged);

      const namedRooms = new Set(described.map((f: any) => String(f.room || "").trim().toLowerCase()).filter(Boolean));
      if (namedRooms.size === 1 && rooms.length > 1) {
        const one = rooms[0];
        one.name = String(described.find((f: any) => String(f.room || "").trim())?.room || one.name).slice(0, 60);
        one.frames = described.map((f: any) => Number(f.n)).filter((n: number) => Number.isFinite(n));
        one.connects = [];
        one.observations = rooms.flatMap(r => r.observations || []).slice(0, 12);
        rooms.length = 0; rooms.push(one);
        root.setAttributes({ "yaadly.sketch.collapsed_to_one_room": true });
      }

      // Drop connections pointing at rooms that do not exist, keeping "outside".
      const keys = new Set(rooms.map(r => r.key));
      for (const r of rooms) r.connects = (r.connects || []).filter(c => c === "outside" || (keys.has(c) && c !== r.key));

      // Every frame must land in exactly one room. Anything the model dropped
      // is reported rather than quietly lost.
      const placed = new Set<number>();
      for (const r of rooms) r.frames = (r.frames || []).filter(f => !placed.has(f) && (placed.add(f), true));
      const orphans = described.map((f: any) => Number(f.n)).filter((n: number) => !placed.has(n));

      const gaps = (Array.isArray(parsed.gaps) ? parsed.gaps : []).map((g: any) => scrub(g, hits).slice(0, 200)).slice(0, 10);
      if (orphans.length) gaps.push(`Photo${orphans.length > 1 ? "s" : ""} ${orphans.join(", ")} could not be placed in a room and ${orphans.length > 1 ? "are" : "is"} not shown on the sketch.`);

      const svg = buildSketch(rooms);
      const summary = scrub(parsed.property_summary, hits).slice(0, 900);

      const numRes = await db(req, "rpc/new_sketch_number", { method: "POST", body: "{}" });
      if (!numRes.ok) return fail(`could not allocate a pack number: http ${numRes.status}`, 502);
      const id = String(await numRes.json());

      const ins = await db(req, "sketch_packs?select=*", {
        method: "POST",
        headers: { Prefer: "return=representation" },
        body: JSON.stringify({
          id,
          job_id: body.job_id || null,
          property_label: String(body.property_label || "Unnamed property").slice(0, 120),
          client_name: String(body.client_name || "").slice(0, 120),
          parish: String(body.parish || "").slice(0, 60),
          visit_date: body.visit_date || null,
          captured_by: String(body.captured_by || "").slice(0, 120),
          conditions: String(body.conditions || "").slice(0, 200),
          job_ref: String(body.job_ref || "").slice(0, 60),
          contractor: String(body.contractor || "").slice(0, 120),
          visit_notes: String(body.visit_notes || "").slice(0, 4000),
          rooms,
          // The still itself travels with its caption now, so the report can
          // print the photograph beside the description. body.images maps
          // still number to a data URI; anything that is not a JPEG or PNG
          // data URI is dropped rather than stored.
          frames: described.map((f: any) => {
            const img = String((body.images || {})[String(f.n)] || "");
            return {
              n: f.n, caption: f.visible, room: f.room, source: "video",
              image: /^data:image\/(jpeg|jpg|png);base64,[A-Za-z0-9+/=]+$/.test(img) && img.length < 600_000 ? img : "",
              observations: (Array.isArray(f.observations) ? f.observations : []).slice(0, 8).map((o: any) => ({
                note: scrub(o.note, hits).slice(0, 260),
                category: ["cosmetic", "maintenance", "safety", "structural", "scope_mismatch"].includes(o.category) ? o.category : "maintenance",
                severity: ["low", "medium", "high"].includes(o.severity) ? o.severity : "low",
                recommend_professional: o.recommend_professional === true || o.category === "safety" || o.category === "structural",
              })),
            };
          }),
          sketch_svg: svg,
          model: `${sketchVisionModel()} + ${prov.model}`,
          model_note: `Frames described by ${sketchVisionModel()}, assembled by ${prov.model}. Sketch geometry generated in code, not by a model. ${hits.length} measurement phrase(s) scrubbed. Not checked by a human yet.`,
        }),
      });
      if (!ins.ok) return fail(`could not store the pack: ${await ins.text()}`, 502);
      const pack = (await ins.json())[0];

      root.setAttributes({
        "yaadly.sketch.pack_id": id,
        "yaadly.sketch.rooms": rooms.length,
        "yaadly.sketch.orphan_frames": orphans.length,
        "yaadly.sketch.measurement_scrubs": hits.length,
      });

      return done(JSON.stringify({
        pack: { ...pack, property_summary: summary, gaps },
        scrubbed: hits,
        orphans,
        reminder: "This is a draft. Nothing has been issued to anybody. Read every room before you approve it.",
      }), 200);
    }

    // ---------------------------------------------------------------- map
    //
    // Type the address, get the map. Founder instruction, 6 September 2026.
    // The address goes to Google's Static Maps service in the United States,
    // which is a new destination for personal data and is named on the
    // privacy page. The image comes back once and is stored on the pack, so
    // the client's document never calls Google itself and the key never
    // leaves this function. Admin only, through the row policies: the update
    // below runs as the caller.
    if (action === "map") {
      const id = String(body.pack_id || "");
      const address = String(body.address || "").trim().slice(0, 200);
      if (!id) return fail("pack_id required", 400);
      if (!address) return fail("Type the address first.", 400);
      // Google if a key is set, OpenStreetMap if not. Keyless is the default
      // on purpose, since 6 September 2026: a map that needs a billing account
      // set up before it works is a map that does not work. Google's aerial
      // imagery is better, so the key still wins when it is there.
      const key = Deno.env.get("GOOGLE_MAPS_API_KEY");
      const dataUri = key ? await googleMap(address, key, trace) : await osmMap(address, trace);
      if (!dataUri) return fail(key
        ? "Google would not give a map for that address. Check the key has the Maps Static API enabled and a billing account behind it, or unset GOOGLE_MAPS_API_KEY to use the free OpenStreetMap map instead."
        : "No map could be made for that address. OpenStreetMap did not recognise it: try it with the parish, or more plainly, for example \"Hope Road, Kingston, Jamaica\".", 502);

      const up = await db(req, `sketch_packs?id=eq.${encodeURIComponent(id)}&select=id,address`, {
        method: "PATCH", headers: { Prefer: "return=representation" },
        body: JSON.stringify({ address, map_image: dataUri }),
      });
      if (!up.ok) return fail(`could not save the map: ${await up.text()}`, 502);
      const rows = await up.json();
      if (!rows.length) return fail("no such pack, or it is not yours to change", 404);
      root.setAttributes({ "yaadly.sketch.pack_id": id, "yaadly.sketch.map_bytes": dataUri.length, "yaadly.sketch.map_source": key ? "google" : "openstreetmap" });
      return done(JSON.stringify({ id, address, map_image: dataUri }), 200);
    }

    // ------------------------------------------------------------- render
    if (action === "render") {
      const id = String(body.pack_id || "");
      if (!id) return fail("pack_id required", 400);
      const [pR, sR] = await Promise.all([
        db(req, `sketch_packs?select=*&id=eq.${encodeURIComponent(id)}`),
        db(req, `app_settings?select=key,value&key=eq.sketch_stamp`),
      ]);
      if (!pR.ok) return fail(`pack read failed: http ${pR.status}`, 502);
      const pack = (await pR.json())[0];
      if (!pack) return fail("no such pack", 404);
      const stamp = sR.ok ? ((await sR.json())[0]?.value ?? "") : "";

      const html = renderPack({ ...pack, property_summary: body.property_summary || pack.property_summary, gaps: body.gaps || [] }, stamp);
      return body.as === "json" ? done(JSON.stringify({ pack, html }), 200) : done(html, 200, "text/html; charset=utf-8");
    }

    return fail(`unknown action: ${action}`, 400);
  } catch (e) {
    root.recordError(e);
    return fail(String(e), 500);
  }
});
