import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { Trace, SpanKind, httpAttrs } from "./otel.ts";

// yaad-sketch
//
// The Site Sketch Pack. A walkthrough video and a set of photos become an
// indicative record of a property: key frames, a room by room condition
// schedule, and a schematic sketch showing rooms, doors and where each photo
// was taken.
//
// THE LINE THIS FUNCTION DOES NOT CROSS.
// It does not measure anything. A phone video carries no scale, so any
// dimension taken from it would be invented, and producing measured drawings
// for reward is regulated work in Jamaica. So: the model is told it has no
// permission to state a dimension, MEASUREMENT_RE scrubs any that appear
// anyway, and has_measurement() in Postgres refuses to let a pack carrying one
// be approved. Three layers, one rule.
//
// The drawing is generated by code, not by the model. The model supplies the
// room list and which rooms connect. Where the boxes land on the page is a
// deterministic layout, which is why it is honest to call it a schematic: it
// shows topology, never geometry.
//
// WHY FRAMES ARRIVE ALREADY EXTRACTED.
// There is no ffmpeg in the edge runtime. Frames are pulled from the video in
// the browser with a <video> element and a canvas, which means the video never
// leaves her machine. Only the frames she chooses are ever uploaded. That is
// the better privacy answer as well as the only workable one.
//
// Actions, in the order the desk calls them:
//   frames    one batch of stills, described by the vision model
//   assemble  all batches, turned into rooms, a sketch and a stored draft
//   render    a pack, turned into the document a client reads

// nvidia/nemotron-nano-12b-v2-vl reached end of life on 26 Aug 2026 and now
// returns HTTP 410. Verified working replacement, checked against a real still
// on the day: it described the shot correctly and refused to call a phone in
// somebody's hand a room, which is the behaviour that matters here.
// Override with the NVIDIA_VISION_MODEL secret; that same secret is read by
// yaad-vision, so setting it fixes both at once.
const VISION_MODEL = Deno.env.get("NVIDIA_VISION_MODEL") || "meta/llama-3.2-90b-vision-instruct";
const VISION_API = "https://integrate.api.nvidia.com/v1/chat/completions";
const TEXT_MODEL = "MiniMax-M2.7";
const TEXT_API = "https://api.minimax.io/v1/chat/completions";

const FRAME_PROMPT = `You are looking at stills taken from a walkthrough video of a property in Jamaica, in the order they were filmed. You are recording what is visibly there, for a project manager who will read it later. You are not a surveyor, an engineer or a valuer.

You will be given several images, numbered. For EACH image, return one object.

Return STRICT JSON only, no markdown fences, exactly this shape:
{"frames":[{"n":1,"room":"plain name for the room or area, e.g. Front bedroom, Kitchen, Rear veranda, Roof","room_confidence":"high|medium|low","same_room_as_previous":true,"visible":"one sentence on what the shot actually shows","doors_to":["names of other rooms or outside that are visibly reachable from here"],"observations":[{"note":"one sentence, only what is visible","category":"cosmetic|maintenance|safety|structural|scope_mismatch","severity":"low|medium|high","recommend_professional":false}]}]}

Rules, all absolute:
1. You may NEVER state a dimension, a distance, an area, a height or a scale. Not in metres, feet, inches, or any other unit. Not even approximately, not even hedged. If size genuinely matters, describe it in words instead: "a hairline crack", "a full height crack", "a small patch", "most of the ceiling". There is no unit of measurement anywhere in your output.
2. Report only what is visible in that image. Never infer a room you cannot see.
3. Never state a structural or safety conclusion with certainty. Use "appears to", "worth checking in person". Anything in the structural or safety category must have recommend_professional set to true.
4. If a shot is too dark, too blurred or too close to judge, say exactly that as the "visible" text and return an empty observations array.
5. Consecutive frames are usually the same room. Set same_room_as_previous honestly, because it is what stitches the walkthrough together.
6. Never name a person, never read out a house number, never transcribe a document or a screen.
7. Do not describe furniture or possessions unless they are the point of the observation.`;

const ASSEMBLE_PROMPT = `You are assembling a walkthrough of a property in Jamaica into a room by room record. You are given, in filming order, what a vision model saw in each still. Your job is to merge duplicates into one room per real room, put them in a sensible order, and say which rooms connect.

Return STRICT JSON only, no markdown fences, exactly this shape:
{"property_summary":"two or three plain sentences describing the property as walked, no opinions on value or price","rooms":[{"key":"short-kebab-key","name":"Front bedroom","level":"ground|upper|outside|roof","walk_order":1,"frames":[1,2],"connects":["hallway"],"observations":[{"note":"","category":"cosmetic|maintenance|safety|structural|scope_mismatch","severity":"low|medium|high","recommend_professional":false}]}],"gaps":["what a reader should know was not filmed or not visible"]}

Rules, all absolute:
1. NEVER state a dimension, distance, area, height or scale, in any unit, anywhere, not even approximately. Describe size in words if it matters.
2. Every frame number you were given must appear in exactly one room's frames array. Do not drop one and do not use one twice.
3. "connects" holds keys of other rooms in your own list, or the literal "outside". Only claim a connection the frames actually support.
4. Merge observations that are plainly the same thing seen twice. Keep the clearer wording. Do not invent new findings.
5. "gaps" is where you are honest about what is missing: a room never entered, a roof never seen, a dark shot. This section is the difference between a record and a sales document.
6. Never name a person and never state an address.`;

// Mirrors has_measurement() in supabase/migrations. If one changes, change
// both. Deliberately excludes bare "in", because "1 in 5 tiles" is English.
const MEASUREMENT_RE =
  /(^|[^a-z0-9])[0-9]+([.,][0-9]+)?\s*(mm|cm|m|m2|m²|metre|meter|metres|meters|ft|foot|feet|yard|yards|inch|inches|sq\.?\s*(m|ft|metre|metres|foot|feet)|square\s+(metre|metres|meter|meters|foot|feet))([^a-z0-9]|$)/i;
const MEASUREMENT_QUOTE_RE = /[0-9]\s*(['"])(\s|$|[.,;)])/;

function hasMeasurement(s: unknown): boolean {
  const t = String(s ?? "");
  return MEASUREMENT_RE.test(t) || MEASUREMENT_QUOTE_RE.test(t);
}

// Anything that slipped past the prompt gets replaced rather than deleted, so
// the sentence still reads and the removal is visible to whoever checks it.
function scrub(s: unknown, hits: string[]): string {
  let t = String(s ?? "");
  if (!hasMeasurement(t)) return t;
  hits.push(t.slice(0, 140));
  t = t.replace(new RegExp(MEASUREMENT_RE.source, "gi"), (m) => m.replace(/[0-9.,]+\s*\S*/, "[size removed]"));
  t = t.replace(new RegExp(MEASUREMENT_QUOTE_RE.source, "g"), " [size removed]$2");
  return t;
}

function bearer(req: Request): string {
  return (req.headers.get("authorization") || "").replace(/^Bearer\s+/i, "");
}
function claim(req: Request, key: string): string {
  try {
    return JSON.parse(atob(bearer(req).split(".")[1].replace(/-/g, "+").replace(/_/g, "/")))[key] || "";
  } catch (_) { return ""; }
}
async function db(req: Request, path: string, init: RequestInit = {}) {
  return await fetch(`${Deno.env.get("SUPABASE_URL")}/rest/v1/${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      apikey: Deno.env.get("SUPABASE_ANON_KEY")!,
      Authorization: `Bearer ${bearer(req)}`,
      ...(init.headers || {}),
    },
  });
}
async function isAdmin(req: Request): Promise<boolean> {
  try {
    const r = await db(req, "rpc/is_admin", { method: "POST", body: "{}" });
    return r.ok && (await r.json()) === true;
  } catch (_) { return false; }
}
const esc = (s: unknown) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));

// --------------------------------------------------------------- the sketch
//
// Rooms are laid out on a snaking grid in walk order, so two rooms visited one
// after the other end up next to each other on the page. Where a connection
// exists between grid neighbours it is drawn as a real gap in the shared wall
// with a door swing. Where it does not, it is a dashed line, which is the
// honest way to say "these connect, but not like this".
//
// There is not a single number on this drawing other than photo markers, and
// those are labelled as photos so they cannot be mistaken for dimensions.

type Room = {
  key: string; name: string; level?: string; walk_order?: number;
  frames?: number[]; connects?: string[];
  observations?: { note: string; category: string; severity: string; recommend_professional?: boolean }[];
};

function buildSketch(rooms: Room[]): string {
  const W = 168, H = 116, GAP = 40, PAD = 34;
  const n = rooms.length;
  if (!n) return "";
  const cols = Math.max(1, Math.min(4, Math.ceil(Math.sqrt(n))));
  const rowCount = Math.ceil(n / cols);

  const pos = new Map<string, { x: number; y: number; col: number; row: number }>();
  rooms.forEach((r, i) => {
    const row = Math.floor(i / cols);
    // Snake, so the walk reads left to right then right to left.
    const col = row % 2 === 0 ? i % cols : cols - 1 - (i % cols);
    pos.set(r.key, { x: PAD + col * (W + GAP), y: PAD + row * (H + GAP), col, row });
  });

  // The stamp at the foot is the most important text on this drawing, so the
  // canvas is never allowed to be narrower than the stamp needs. A cut-off
  // disclaimer is worse than no disclaimer.
  const width = Math.max(660, PAD * 2 + cols * W + (cols - 1) * GAP);
  const height = PAD * 2 + rowCount * H + (rowCount - 1) * GAP + 84;

  const parts: string[] = [];

  // Connections first, so rooms draw on top of them.
  const drawn = new Set<string>();
  for (const r of rooms) {
    for (const c of r.connects || []) {
      if (c === "outside") continue;
      const pair = [r.key, c].sort().join("|");
      if (drawn.has(pair)) continue;
      const a = pos.get(r.key), b = pos.get(c);
      if (!a || !b) continue;
      drawn.add(pair);

      const sameRow = a.row === b.row && Math.abs(a.col - b.col) === 1;
      const sameCol = a.col === b.col && Math.abs(a.row - b.row) === 1;

      if (sameRow) {
        const x = Math.max(a.x, b.x);          // left edge of the right-hand room
        const y = a.y + H / 2;
        parts.push(`<rect x="${x - GAP - 1}" y="${y - 17}" width="${GAP + 2}" height="34" fill="#fff"/>`);
        parts.push(`<path d="M ${x - GAP} ${y - 17} A 34 34 0 0 1 ${x} ${y + 17}" fill="none" stroke="#B7C9C3" stroke-width="1.4"/>`);
      } else if (sameCol) {
        const y = Math.max(a.y, b.y);
        const x = a.x + W / 2;
        parts.push(`<rect x="${x - 17}" y="${y - GAP - 1}" width="34" height="${GAP + 2}" fill="#fff"/>`);
        parts.push(`<path d="M ${x - 17} ${y - GAP} A 34 34 0 0 0 ${x + 17} ${y}" fill="none" stroke="#B7C9C3" stroke-width="1.4"/>`);
      } else {
        parts.push(`<line x1="${a.x + W / 2}" y1="${a.y + H / 2}" x2="${b.x + W / 2}" y2="${b.y + H / 2}" stroke="#C6D6D1" stroke-width="1.4" stroke-dasharray="5 5"/>`);
      }
    }
  }

  rooms.forEach((r) => {
    const p = pos.get(r.key)!;
    const outside = (r.connects || []).includes("outside");
    parts.push(`<rect x="${p.x}" y="${p.y}" width="${W}" height="${H}" fill="#FBFDFC" stroke="#0F1B17" stroke-width="2" rx="3"/>`);
    if (outside) {
      parts.push(`<rect x="${p.x + W / 2 - 17}" y="${p.y + H - 2}" width="34" height="4" fill="#fff"/>`);
      parts.push(`<text x="${p.x + W / 2}" y="${p.y + H + 17}" text-anchor="middle" font-size="10" fill="#67807A" font-family="'Space Grotesk',sans-serif">outside</text>`);
    }
    const name = esc(r.name).slice(0, 26);
    parts.push(`<text x="${p.x + 12}" y="${p.y + 24}" font-size="13" font-weight="700" fill="#0F1B17" font-family="'Space Grotesk',sans-serif">${name}</text>`);
    if (r.level && r.level !== "ground") {
      parts.push(`<text x="${p.x + 12}" y="${p.y + 40}" font-size="10" fill="#67807A" font-family="'Space Grotesk',sans-serif">${esc(r.level)}</text>`);
    }
    (r.frames || []).slice(0, 8).forEach((f, i) => {
      const cx = p.x + 22 + (i % 4) * 30, cy = p.y + H - 34 + Math.floor(i / 4) * 26;
      parts.push(`<circle cx="${cx}" cy="${cy}" r="11" fill="#14B8A6"/>`);
      parts.push(`<text x="${cx}" y="${cy + 4}" text-anchor="middle" font-size="10" font-weight="700" fill="#04120F" font-family="'Space Grotesk',sans-serif">${f}</text>`);
    });
  });

  const legendY = PAD + rowCount * H + (rowCount - 1) * GAP + 42;
  parts.push(`<circle cx="${PAD + 11}" cy="${legendY - 4}" r="11" fill="#14B8A6"/>`);
  parts.push(`<text x="${PAD + 11}" y="${legendY}" text-anchor="middle" font-size="10" font-weight="700" fill="#04120F" font-family="'Space Grotesk',sans-serif">n</text>`);
  parts.push(`<text x="${PAD + 30}" y="${legendY}" font-size="11" fill="#4A5F5A" font-family="'Space Grotesk',sans-serif">where photo n was taken</text>`);
  // Two short lines rather than one long one, so it fits at any room count.
  parts.push(`<text x="${PAD}" y="${legendY + 22}" font-size="11" fill="#8A5A00" font-family="'Space Grotesk',sans-serif">Schematic only. Rooms are drawn the same size whatever their real size.</text>`);
  parts.push(`<text x="${PAD}" y="${legendY + 37}" font-size="11" fill="#8A5A00" font-family="'Space Grotesk',sans-serif">Nothing here is to scale and nothing has been measured.</text>`);

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="100%" role="img" aria-label="Schematic sketch of the rooms walked, not to scale">
<rect width="${width}" height="${height}" fill="#fff"/>
${parts.join("\n")}
</svg>`;
}

// --------------------------------------------------------------- pack render

function renderPack(p: Record<string, any>, stamp: string): string {
  const rooms: Room[] = p.rooms || [];
  const frames: any[] = p.frames || [];
  const sev = (s: string) => ({ high: "#B42318", medium: "#8A5A00", low: "#4A5F5A" }[s] || "#4A5F5A");
  const escalating = rooms.flatMap(r => r.observations || []).filter(o => o.recommend_professional || o.category === "structural" || o.category === "safety");

  const roomBlocks = rooms.map((r) => `
    <section class="room">
      <h3>${esc(r.name)}${r.level && r.level !== "ground" ? ` <span class="lvl">${esc(r.level)}</span>` : ""}</h3>
      <div class="shots">${(r.frames || []).map(f => `<span class="shot">photo ${f}</span>`).join("")}</div>
      ${(r.observations || []).length ? `<ul>${(r.observations || []).map(o => `
        <li><span class="dot" style="background:${sev(o.severity)}"></span>
        <b>${esc(o.category.replace("_", " "))}, ${esc(o.severity)}</b>. ${esc(o.note)}
        ${o.recommend_professional ? '<em class="pro">Worth a qualified person looking at this in person.</em>' : ""}</li>`).join("")}</ul>`
        : `<p class="none">Nothing notable visible in what was filmed here.</p>`}
    </section>`).join("");

  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(p.id)} · Site Sketch Pack</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Space+Grotesk:wght@400;500;700&display=swap" rel="stylesheet">
<style>
:root{--teal:#14B8A6;--deep:#08110F;--line:#DCE6E2;--mute:#5E7772}
*{box-sizing:border-box}
body{margin:0;padding:32px 20px;background:#F4F7F6;color:var(--deep);font:15px/1.6 'Space Grotesk',-apple-system,sans-serif}
.sheet{max-width:820px;margin:0 auto;background:#fff;padding:44px 48px;border-radius:14px;box-shadow:0 2px 24px rgba(8,17,15,.08)}
header{border-bottom:3px solid var(--teal);padding-bottom:20px;display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}
.mark{font-family:'Anton',Impact,sans-serif;font-size:32px;line-height:1}.mark span{color:var(--teal)}
h1{font-family:'Anton',Impact,sans-serif;font-weight:400;font-size:26px;margin:0;letter-spacing:.6px}
.ref{font-size:15px;font-weight:700;color:var(--mute)}
.stamp{margin:22px 0;padding:15px 18px;background:#FFFBF2;border:1px solid #FFE0A3;border-radius:9px;color:#8A5A00;font-size:13.5px}
.meta{display:flex;gap:30px;flex-wrap:wrap;margin:22px 0}
.meta h2{font-size:10px;letter-spacing:1.4px;text-transform:uppercase;color:var(--mute);margin:0 0 4px}
.meta p{margin:0}
h2.sec{font-family:'Anton',Impact,sans-serif;font-weight:400;font-size:19px;letter-spacing:.7px;margin:34px 0 12px;padding-top:18px;border-top:1px solid var(--line)}
.summary{font-size:16px}
.sketch{border:1px solid var(--line);border-radius:10px;padding:14px;background:#fff;overflow-x:auto}
.room{padding:16px 0;border-bottom:1px solid var(--line)}
.room h3{margin:0 0 6px;font-size:16px}
.lvl{font-size:11px;color:var(--mute);font-weight:400;text-transform:uppercase;letter-spacing:1.1px}
.shots{margin-bottom:8px}
.shot{display:inline-block;background:#E8F6F4;color:#0B7A6E;border-radius:999px;padding:2px 10px;font-size:11px;font-weight:700;margin-right:6px}
.room ul{margin:0;padding:0;list-style:none}
.room li{padding:7px 0 7px 20px;position:relative;font-size:14.5px}
.dot{position:absolute;left:0;top:14px;width:9px;height:9px;border-radius:50%}
.pro{display:block;color:#B42318;font-style:normal;font-size:13px;margin-top:2px}
.none{color:var(--mute);font-size:14px;margin:0}
.gaps{background:#F4F7F6;border-left:3px solid var(--teal);padding:14px 18px;border-radius:0 9px 9px 0}
.gaps ul{margin:6px 0 0;padding-left:18px}
.esc{background:#FEF3F2;border:1px solid #FDA29B;border-radius:9px;padding:14px 18px;color:#B42318;font-size:14px}
footer{margin-top:34px;padding-top:18px;border-top:1px solid var(--line);font-size:12px;color:var(--mute);line-height:1.75}
@media print{body{background:#fff;padding:0}.sheet{box-shadow:none;padding:0;max-width:none}}
</style></head><body><div class="sheet">
<header>
  <div><div class="mark">YAADLY<span>.</span></div><div class="ref">Site Sketch Pack</div></div>
  <div style="text-align:right"><h1>${esc(p.property_label)}</h1><div class="ref">${esc(p.id)}${p.rev > 1 ? ` rev ${esc(p.rev)}` : ""}</div></div>
</header>

<div class="stamp"><b>Read this first.</b> ${esc(stamp)}</div>

<div class="meta">
  ${p.client_name ? `<div><h2>Prepared for</h2><p>${esc(p.client_name)}</p></div>` : ""}
  ${p.parish ? `<div><h2>Parish</h2><p>${esc(p.parish)}</p></div>` : ""}
  ${p.visit_date ? `<div><h2>Filmed</h2><p>${esc(p.visit_date)}</p></div>` : ""}
  ${p.captured_by ? `<div><h2>Walked by</h2><p>${esc(p.captured_by)}</p></div>` : ""}
  <div><h2>Status</h2><p>${esc(p.status)}</p></div>
</div>

${p.property_summary ? `<h2 class="sec">What was walked</h2><p class="summary">${esc(p.property_summary)}</p>` : ""}

${p.sketch_svg ? `<h2 class="sec">Schematic sketch</h2><div class="sketch">${p.sketch_svg}</div>` : ""}

<h2 class="sec">Room by room</h2>
${roomBlocks || "<p class='none'>No rooms recorded.</p>"}

${escalating.length ? `<h2 class="sec">Worth a qualified person seeing</h2>
<div class="esc">${escalating.length} observation${escalating.length > 1 ? "s" : ""} in this pack fall${escalating.length > 1 ? "" : "s"} outside what can be judged from a photograph. They are marked in the schedule above. This pack does not tell you how serious they are, only that they are there.</div>` : ""}

${(p.gaps || []).length ? `<h2 class="sec">What this pack does not cover</h2>
<div class="gaps">Filmed on one visit, so it records only what was walked and lit at the time.<ul>${(p.gaps || []).map((g: string) => `<li>${esc(g)}</li>`).join("")}</ul></div>` : ""}

<h2 class="sec">Photographs</h2>
<div class="shots">${frames.map((f: any) => `<span class="shot">photo ${esc(f.n)}</span>`).join("")}</div>
<p class="none">${frames.length} still${frames.length === 1 ? "" : "s"} taken from the walkthrough video. The images accompany this pack.</p>

<footer>
  ${esc(stamp)}<br>
  Yaadly Ltd, registered in England and Wales, company number 17358077.<br>
  This document records observation and documentation only. It is not a survey, a structural report, a valuation, a legal opinion or a quantity surveyor's estimate, and nothing in it should be relied on as one. Findings reflect conditions visible on the day of filming.
</footer>
</div></body></html>`;
}

// --------------------------------------------------------------- handler

Deno.serve(async (req) => {
  const cors = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
  };
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });

  const trace = new Trace("yaad-sketch", req);
  const root = trace.startSpan("POST /yaad-sketch", SpanKind.SERVER, httpAttrs(req));
  const done = (body: BodyInit, status: number, ct = "application/json") => {
    root.setAttributes({ "http.response.status_code": status });
    root.end(); trace.flush();
    return new Response(body, { status, headers: { ...cors, "Content-Type": ct } });
  };
  const fail = (m: string, s: number) => done(JSON.stringify({ error: m }), s);

  try {
    if (claim(req, "role") !== "authenticated") {
      root.setAttributes({ "yaadly.auth.outcome": "rejected" });
      return fail("Sign in required.", 401);
    }
    if (!(await isAdmin(req))) {
      root.setAttributes({ "yaadly.auth.outcome": "not_admin" });
      return fail("Admin only.", 403);
    }
    root.setAttributes({ "yaadly.auth.outcome": "admin" });

    const body = await req.json().catch(() => ({}));
    const action = String(body.action || "");
    root.setAttributes({ "yaadly.sketch.action": action });

    // ------------------------------------------------------------- frames
    if (action === "frames") {
      const key = Deno.env.get("NVIDIA_API_KEY");
      if (!key) return fail("NVIDIA_API_KEY is not set on this project, so the vision model cannot be reached.", 500);

      const images: string[] = Array.isArray(body.images) ? body.images.slice(0, 6) : [];
      const startAt = Number(body.start_at) || 1;
      if (!images.length) return fail("No frames in this batch.", 400);

      const content: Record<string, unknown>[] = [{
        type: "text",
        text: `These are stills ${startAt} to ${startAt + images.length - 1} from the walkthrough, in filming order. Number them from ${startAt}. ${body.context ? "Context from the person who filmed it: " + String(body.context).slice(0, 400) : ""}`,
      }];
      for (const img of images) content.push({ type: "image_url", image_url: { url: img } });

      const raw = await trace.span(`chat ${VISION_MODEL}`, SpanKind.CLIENT, {
        "gen_ai.system": "nvidia_nim",
        "gen_ai.operation.name": "chat",
        "gen_ai.request.model": VISION_MODEL,
        "gen_ai.request.temperature": 0.2,
        "server.address": "integrate.api.nvidia.com",
        "yaadly.sketch.batch_size": images.length,
      }, async (s) => {
        const r = await fetch(VISION_API, {
          method: "POST",
          headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            model: VISION_MODEL,
            messages: [{ role: "system", content: FRAME_PROMPT }, { role: "user", content }],
            max_tokens: 1800, temperature: 0.2,
          }),
        });
        const body = await r.text();
        let j: any = {};
        try { j = JSON.parse(body); } catch (_) { /* keep the raw text */ }
        s.setAttributes({
          "http.response.status_code": r.status,
          "gen_ai.usage.input_tokens": j?.usage?.prompt_tokens,
          "gen_ai.usage.output_tokens": j?.usage?.completion_tokens,
        });
        if (!r.ok) s.recordError(`nvidia http ${r.status}: ${body.slice(0, 200)}`);
        // A failed model call must never come back looking like "the model saw
        // nothing". That reads as a clean result and it is not one.
        return { ok: r.ok, status: r.status, body, content: j?.choices?.[0]?.message?.content ?? "" };
      });

      if (!raw.ok) {
        root.setAttributes({ "yaadly.sketch.outcome": "model_error" });
        return fail(`The vision model refused the request (HTTP ${raw.status}). It said: ${raw.body.slice(0, 300)}`, 502);
      }
      if (!String(raw.content).trim()) {
        root.setAttributes({ "yaadly.sketch.outcome": "empty_response" });
        return fail(`The vision model returned an empty answer. Raw response: ${raw.body.slice(0, 300)}`, 502);
      }

      let parsed: any = {};
      try {
        const m = String(raw.content).match(/\{[\s\S]*\}/);
        if (!m) throw new Error("no JSON object in the answer");
        parsed = JSON.parse(m[0]);
      } catch (_) {
        root.setAttributes({ "yaadly.sketch.outcome": "unparseable" });
        return fail(`The vision model answered, but not in JSON. It said: ${String(raw.content).slice(0, 300)}`, 502);
      }
      if (!Array.isArray(parsed.frames) || !parsed.frames.length) {
        root.setAttributes({ "yaadly.sketch.outcome": "no_frames" });
        return fail(`The vision model returned no frame entries. It said: ${String(raw.content).slice(0, 300)}`, 502);
      }

      const hits: string[] = [];
      const out = (parsed.frames || []).map((f: any, i: number) => ({
        n: Number(f.n) || startAt + i,
        room: scrub(f.room, hits).slice(0, 60),
        room_confidence: ["high", "medium", "low"].includes(f.room_confidence) ? f.room_confidence : "low",
        same_room_as_previous: f.same_room_as_previous === true,
        visible: scrub(f.visible, hits).slice(0, 300),
        doors_to: Array.isArray(f.doors_to) ? f.doors_to.map((d: any) => String(d).slice(0, 40)).slice(0, 6) : [],
        observations: (Array.isArray(f.observations) ? f.observations : []).slice(0, 8).map((o: any) => ({
          note: scrub(o.note, hits).slice(0, 260),
          category: ["cosmetic", "maintenance", "safety", "structural", "scope_mismatch"].includes(o.category) ? o.category : "maintenance",
          severity: ["low", "medium", "high"].includes(o.severity) ? o.severity : "low",
          recommend_professional: o.recommend_professional === true || o.category === "safety" || o.category === "structural",
        })),
      }));

      root.setAttributes({ "yaadly.sketch.frames_described": out.length, "yaadly.sketch.measurement_scrubs": hits.length });
      return done(JSON.stringify({ frames: out, scrubbed: hits }), 200);
    }

    // ----------------------------------------------------------- assemble
    if (action === "assemble") {
      const key = Deno.env.get("MINIMAX_API_KEY");
      if (!key) return fail("MINIMAX_API_KEY is not set on this project.", 500);
      const described: any[] = Array.isArray(body.frames) ? body.frames : [];
      if (!described.length) return fail("Nothing to assemble: describe the frames first.", 400);

      const raw = await trace.span(`chat ${TEXT_MODEL}`, SpanKind.CLIENT, {
        "gen_ai.system": "minimax",
        "gen_ai.operation.name": "chat",
        "gen_ai.request.model": TEXT_MODEL,
        "gen_ai.request.temperature": 0.1,
        "server.address": "api.minimax.io",
      }, async (s) => {
        const r = await fetch(TEXT_API, {
          method: "POST",
          headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            model: TEXT_MODEL, temperature: 0.1,
            messages: [
              { role: "system", content: ASSEMBLE_PROMPT },
              { role: "user", content: JSON.stringify({ property: String(body.property_label || ""), frames: described }).slice(0, 24000) },
            ],
          }),
        });
        const body = await r.text();
        let j: any = {};
        try { j = JSON.parse(body); } catch (_) { /* keep the raw text */ }
        s.setAttributes({
          "http.response.status_code": r.status,
          "gen_ai.usage.input_tokens": j?.usage?.prompt_tokens,
          "gen_ai.usage.output_tokens": j?.usage?.completion_tokens,
        });
        if (!r.ok) s.recordError(`minimax http ${r.status}: ${body.slice(0, 200)}`);
        return { ok: r.ok, status: r.status, body, content: j?.choices?.[0]?.message?.content ?? "" };
      });

      if (!raw.ok) return fail(`The assembly model refused the request (HTTP ${raw.status}). It said: ${raw.body.slice(0, 300)}`, 502);
      if (!String(raw.content).trim()) return fail(`The assembly model returned an empty answer. Raw response: ${raw.body.slice(0, 300)}`, 502);

      let parsed: any = {};
      try {
        const m = String(raw.content).match(/\{[\s\S]*\}/);
        if (!m) throw new Error("no JSON object in the answer");
        parsed = JSON.parse(m[0]);
      } catch (_) {
        return fail(`The assembly model answered, but not in JSON. It said: ${String(raw.content).slice(0, 300)}`, 502);
      }

      const hits: string[] = [];
      const seenKeys = new Set<string>();
      const rooms: Room[] = (Array.isArray(parsed.rooms) ? parsed.rooms : []).slice(0, 30).map((r: any, i: number) => {
        let k = String(r.key || r.name || `room-${i + 1}`).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40) || `room-${i + 1}`;
        while (seenKeys.has(k)) k = k + "-2";
        seenKeys.add(k);
        return {
          key: k,
          name: scrub(r.name, hits).slice(0, 60) || `Room ${i + 1}`,
          level: ["ground", "upper", "outside", "roof"].includes(r.level) ? r.level : "ground",
          walk_order: Number(r.walk_order) || i + 1,
          frames: (Array.isArray(r.frames) ? r.frames : []).map((f: any) => Number(f)).filter((f: number) => Number.isFinite(f)),
          connects: (Array.isArray(r.connects) ? r.connects : []).map((c: any) => String(c).toLowerCase().replace(/[^a-z0-9]+/g, "-")).slice(0, 8),
          observations: (Array.isArray(r.observations) ? r.observations : []).slice(0, 12).map((o: any) => ({
            note: scrub(o.note, hits).slice(0, 260),
            category: ["cosmetic", "maintenance", "safety", "structural", "scope_mismatch"].includes(o.category) ? o.category : "maintenance",
            severity: ["low", "medium", "high"].includes(o.severity) ? o.severity : "low",
            recommend_professional: o.recommend_professional === true || o.category === "safety" || o.category === "structural",
          })),
        };
      });

      if (!rooms.length) return fail("The assembly step found no rooms in those frames.", 422);
      rooms.sort((a, b) => (a.walk_order || 0) - (b.walk_order || 0));

      // Drop connections pointing at rooms that do not exist, keeping "outside".
      const keys = new Set(rooms.map(r => r.key));
      for (const r of rooms) r.connects = (r.connects || []).filter(c => c === "outside" || (keys.has(c) && c !== r.key));

      // Every frame must land in exactly one room. Anything the model dropped
      // is reported rather than quietly lost.
      const placed = new Set<number>();
      for (const r of rooms) r.frames = (r.frames || []).filter(f => !placed.has(f) && (placed.add(f), true));
      const orphans = described.map((f: any) => Number(f.n)).filter((n: number) => !placed.has(n));

      const gaps = (Array.isArray(parsed.gaps) ? parsed.gaps : []).map((g: any) => scrub(g, hits).slice(0, 200)).slice(0, 10);
      if (orphans.length) gaps.push(`Photo${orphans.length > 1 ? "s" : ""} ${orphans.join(", ")} could not be placed in a room and ${orphans.length > 1 ? "are" : "is"} not shown on the sketch.`);

      const svg = buildSketch(rooms);
      const summary = scrub(parsed.property_summary, hits).slice(0, 900);

      const numRes = await db(req, "rpc/new_sketch_number", { method: "POST", body: "{}" });
      if (!numRes.ok) return fail(`could not allocate a pack number: http ${numRes.status}`, 502);
      const id = String(await numRes.json());

      const ins = await db(req, "sketch_packs?select=*", {
        method: "POST",
        headers: { Prefer: "return=representation" },
        body: JSON.stringify({
          id,
          job_id: body.job_id || null,
          property_label: String(body.property_label || "Unnamed property").slice(0, 120),
          client_name: String(body.client_name || "").slice(0, 120),
          parish: String(body.parish || "").slice(0, 60),
          visit_date: body.visit_date || null,
          captured_by: String(body.captured_by || "").slice(0, 120),
          rooms,
          frames: described.map((f: any) => ({ n: f.n, caption: f.visible, room: f.room, source: "video" })),
          sketch_svg: svg,
          model: `${VISION_MODEL} + ${TEXT_MODEL}`,
          model_note: `Frames described by ${VISION_MODEL}, assembled by ${TEXT_MODEL}. Sketch geometry generated in code, not by a model. ${hits.length} measurement phrase(s) scrubbed. Not checked by a human yet.`,
        }),
      });
      if (!ins.ok) return fail(`could not store the pack: ${await ins.text()}`, 502);
      const pack = (await ins.json())[0];

      root.setAttributes({
        "yaadly.sketch.pack_id": id,
        "yaadly.sketch.rooms": rooms.length,
        "yaadly.sketch.orphan_frames": orphans.length,
        "yaadly.sketch.measurement_scrubs": hits.length,
      });

      return done(JSON.stringify({
        pack: { ...pack, property_summary: summary, gaps },
        scrubbed: hits,
        orphans,
        reminder: "This is a draft. Nothing has been issued to anybody. Read every room before you approve it.",
      }), 200);
    }

    // ------------------------------------------------------------- render
    if (action === "render") {
      const id = String(body.pack_id || "");
      if (!id) return fail("pack_id required", 400);
      const [pR, sR] = await Promise.all([
        db(req, `sketch_packs?select=*&id=eq.${encodeURIComponent(id)}`),
        db(req, `app_settings?select=key,value&key=eq.sketch_stamp`),
      ]);
      if (!pR.ok) return fail(`pack read failed: http ${pR.status}`, 502);
      const pack = (await pR.json())[0];
      if (!pack) return fail("no such pack", 404);
      const stamp = sR.ok ? ((await sR.json())[0]?.value ?? "") : "";

      const html = renderPack({ ...pack, property_summary: body.property_summary || pack.property_summary, gaps: body.gaps || [] }, stamp);
      return body.as === "json" ? done(JSON.stringify({ pack, html }), 200) : done(html, 200, "text/html; charset=utf-8");
    }

    return fail(`unknown action: ${action}`, 400);
  } catch (e) {
    root.recordError(e);
    return fail(String(e), 500);
  }
});
